; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "LetMeShutdown"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "bartekl1"
#define MyAppURL "https://github.com/bartekl1/LetMeShutdown"
#define MyAppExeName "LetMeShutdown.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{AC224676-06C7-45FC-AA39-273011D0BE3E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppPublisher}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppPublisher}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DefaultGroupName={#MyAppName}
LicenseFile=LICENSE
; InfoBeforeFile=InstallerNote.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=Output
OutputBaseFilename={#MyAppName}-Setup
SolidCompression=yes
WizardStyle=modern dynamic
DisableWelcomePage=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
; Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"; InfoBeforeFile: "InstallerNote.pl.txt"
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"

[Files]
Source: "{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "task.xml"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

; [Icons]
; Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"

[Run]
; Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "schtasks.exe"; Parameters: "/create /xml ""{app}\task.xml"" /tn LetMeShutdown /f"; Flags: runhidden
Filename: "schtasks.exe"; Parameters: "/change /tn LetMeShutdown /tr ""'{app}\{#MyAppExeName}'"""; Flags: runhidden
Filename: "schtasks.exe"; Parameters: "/run /tn LetMeShutdown"; Flags: runhidden

[UninstallRun]
Filename: "schtasks.exe"; Parameters: "/end /tn LetMeShutdown"; Flags: runhidden
Filename: "taskkill.exe"; Parameters: "/im {#MyAppExeName} /f"; Flags: runhidden
Filename: "schtasks.exe"; Parameters: "/delete /tn LetMeShutdown /f"; Flags: runhidden

[Code]
procedure InitializeWizard;
begin
  WizardForm.LicenseAcceptedRadio.Checked := True;
end;
